/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        accent: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
        },
        theme: {
          primary: 'var(--theme-primary)',
          'primary-light': 'var(--theme-primary-light)',
          'primary-dark': 'var(--theme-primary-dark)',
          secondary: 'var(--theme-secondary)',
          'secondary-light': 'var(--theme-secondary-light)',
          'secondary-dark': 'var(--theme-secondary-dark)',
          accent: 'var(--theme-accent)',
          'accent-light': 'var(--theme-accent-light)',
          'accent-dark': 'var(--theme-accent-dark)',
          'gradient-start': 'var(--theme-gradient-start)',
          'gradient-middle': 'var(--theme-gradient-middle)',
          'gradient-end': 'var(--theme-gradient-end)',
          'bg-start': 'var(--theme-bg-start)',
          'bg-middle': 'var(--theme-bg-middle)',
          'bg-end': 'var(--theme-bg-end)',
          'text-primary': 'var(--theme-text-primary)',
          'text-secondary': 'var(--theme-text-secondary)',
          'text-accent': 'var(--theme-text-accent)',
          border: 'var(--theme-border)',
          sidebar: 'var(--theme-sidebar)',
          'sidebar-hover': 'var(--theme-sidebar-hover)',
          'input-area': 'var(--theme-input-area)',
          'input-bg': 'var(--theme-input-bg)',
          'bubble-assistant': 'var(--theme-bubble-assistant)',
          'bubble-assistant-border': 'var(--theme-bubble-assistant-border)',
          'card-bg': 'var(--theme-card-bg)',
          'card-hover': 'var(--theme-card-hover)',
          overlay: 'var(--theme-overlay)',
          'action-icon': 'var(--theme-action-icon)',
          'action-icon-hover': 'var(--theme-action-icon-hover)',
          danger: 'var(--theme-danger)',
          'danger-light': 'var(--theme-danger-light)',
          'danger-bg': 'var(--theme-danger-bg)',
          success: 'var(--theme-success)',
          'success-light': 'var(--theme-success-light)',
          'success-bg': 'var(--theme-success-bg)',
          'menu-bg': 'var(--theme-menu-bg)',
          shadow: 'var(--theme-shadow)',
          'shadow-light': 'var(--theme-shadow-light)',
        },
      },
      boxShadow: {
        'card': '0 4px 6px -1px var(--theme-shadow), 0 2px 4px -1px var(--theme-shadow-light)',
        'glow': '0 0 20px var(--theme-primary)',
        'soft': '0 10px 40px -10px var(--theme-shadow)',
        'theme-glow': '0 0 20px var(--theme-primary)',
        'theme-soft': '0 10px 40px -10px var(--theme-primary)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
